version: "3.8"

services:
  backend:
    build:
      context: ./documentqa_backend
    env_file:
      - ./documentqa_backend/.env
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./documentqa_backend:/app
    depends_on:
      - postgres
      - redis
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 documentqa_backend.wsgi:application"
    networks:
      - app_network

  frontend:
    build:
      context: ./documentqa_frontend
    ports:
      - "8080:80" # Serve frontend via Nginx
    depends_on:
      - backend
    networks:
      - app_network

  postgres:
    image: postgres:17.2
    env_file:
      - ./documentqa_backend/.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery:
    build:
      context: ./documentqa_backend
    command: celery -A documentqa_backend worker --loglevel=info
    depends_on:
      - redis
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
