# Generated by Django 5.1.4 on 2025-01-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
